# Keras
Keras is a python library that builds on the top of TensorFlow
It helpers for creating a pipeline (workflow) for building and training the tensorflow model

# The Sequential model
A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor. The layers are used as a pipeline to build/train the model.

In [1]:
import tensorflow as tf
from tensorflow import keras
from keras import layers

# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ])

# Call model on a test input
x = tf.ones((3, 3))
y = model(x)
y


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.3935445 ,  0.34656996, -0.7464288 ,  0.72775453],
       [ 0.3935445 ,  0.34656996, -0.7464288 ,  0.72775453],
       [ 0.3935445 ,  0.34656996, -0.7464288 ,  0.72775453]],
      dtype=float32)>

You can also do the same thing without using a sequential model:

In [3]:
# Create 3 layers
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
print(layer1(x))

# In a model the output of one layer is used as input in the next layer as we can simulate here
y = layer3(layer2(layer1(x)))
y

tf.Tensor(
[[0.         0.09370887]
 [0.         0.09370887]
 [0.         0.09370887]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.01194037,  0.06347702, -0.119874  ,  0.00721825],
       [-0.01194037,  0.06347702, -0.119874  ,  0.00721825],
       [-0.01194037,  0.06347702, -0.119874  ,  0.00721825]],
      dtype=float32)>

Advanced: If you have more than one input Tensor you cannot use the Sequential model and need to use the Functional API

In [ ]:
#advanced example defining you own inputs
inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

# But what does the layers.Dense() function do?

[Neural Networks explained (youtube deeplizard)](https://youtu.be/sZAlS3_dnk0)


A Dense layer feeds all outputs from the previous layer to all its neurons, each neuron providing one output to the next layer. It's the most basic layer in neural networks. A Dense(10) has ten neurons.

These are the terms you need to study to better understand a neural network
* [Weights]()
* [Loss](https://youtu.be/Skc8nqJirJg) function (uses [Gradients](2_tensor_basics.ipynb#Gradients))
* [How is the network learning](https://youtu.be/_N5kpSMDf4o)
* [Backpropagation(optional)](https://youtu.be/sZAlS3_dnk0) (uses learnable variables)
* [Bias(optional)](https://youtu.be/HetFihsXSys)


It is also a delegate function you can configure by specifying the parameters of the Dense function:

output = activation(dot(input, kernel) + bias)

where
* input: represent the input data
* kernel: represent the weight data
* dot: represent numpy dot product of all input and its corresponding weights
* bias: represent a biased value used in machine learning to optimize the model
* activation: represent the activation function.

This is what the function "dot(input, kernel)" in a Dense layer looks like:

In [ ]:
import numpy as np 
input = [ [1, 2], [3, 4] ] 
kernel = [ [0.5, 0.75], [0.25, 0.5] ] 
result = np.dot(input, kernel) # product of 2 arrays
result # array([[1. , 1.75], [2.5 , 4.25]])

Examining the model layers input and output

In [ ]:
print(model.summary())

Examining input and ouput

*There is no argument available to specify the input_shape of the input data. 
input_shape is a special argument, which the layer will accept only if it is designed as first layer in the model.*


In [ ]:
print("layer0:input",model.layers[0].input_shape)
print("layer0:output",model.layers[0].output_shape)
print("               v v ")
print("layer1:input",model.layers[1].input_shape)
print("layer1:output",model.layers[1].output_shape)
print("               v v ")
print("layer2:input",model.layers[2].input_shape)
print("layer2:output",model.layers[2].output_shape, "\n")

print("layer0:weights", model.layers[0].get_weights())
print("layer1:weights",model.layers[1].get_weights())

#print("layer1:config",model.layers[1].get_config())


add one layer and use model.predict to get result 

conv2d gives a list of feature maps

https://pysource.com/2022/08/02/feature-map-computer-vision-with-keras-p-4/

extract features each feature extracts one characteristic of the thing where trying to find